theme: beautiful-jekyll
title: Daniel Bauman
description: PhD Student in Computational Mathematics at Stanford University
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
kramdown:
  math_engine: mathjax
navbar-links:
  Blog: "blog"
  About Me: "index"
  Publications: "publications"
