theme: minima
title: Daniel Bauman
description: PhD Student in Computational Mathematics at Stanford University

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

markdown: kramdown
kramdown:
  math_engine: mathjax

# Explicitly control which pages show up in the navigation bar
header_pages:
  - index.md
  - research.md
  - blog/index.md

paginate: 3
paginate_path: "/blog/page:num"
