theme: minima
title: Daniel Bauman
author: Daniel Bauman
description: PhD Student in Computational Mathematics at Stanford University
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
kramdown:
  math_engine: mathjax
